# Generated by Django 5.1.1 on 2024-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
