# Generated by Django 5.1.1 on 2024-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_milkrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='litres',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
